# Site settings
title: Mark Woo Home
header-img: img/home-bg.jpg
email: wcgwuxinwei@gmail.com
description: "Mark Woo's Personal Blog"
baseurl: ""
url: "http://wuxinwei.org"
twitter_username:   wcgwuxinwei
github_username:    wuxinwei
facebook_username:  mark.woo.1990

# Build settings
# markdown: kramdown
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
